site_name: Quokka

nav:
        - Home: index.md
        - Getting Started: started.md
        - Setting Up Cloud Cluster: cloud.md
        - Tutorials: simple.md
        - Advanced Tutorials: tutorial.md
        - Dataframe API reference: api.md

theme: readthedocs

