site_name: Quokka

nav:
        - Home: index.md
        - Getting Started: started.md
        - Setting Up Cloud Cluster: cloud.md
        - Tutorials: 
                - DataStream API: simple.md
                - TaskGraph API: tutorial.md
        - Dataframe API reference: 
                - QuokkaContext: quokka_context.md
                - DataStream: datastream.md

theme: readthedocs

