site_name: Quokka
repo_url: https://github.com/marsupialtail/quokka

nav:
        - Home: index.md
        - Cartoons: started.md
        - Installation: install.md
        - Setting Up Cloud Cluster: cloud.md
        - How is Quokka different from ...?: different.md
        - Tutorials: 
                - DataStream API: simple.md
                - TaskGraph API: tutorial.md
        - Dataframe API reference: 
                - QuokkaContext: quokka_context.md
                - DataStream: datastream.md
        

theme: readthedocs

